03-13 15:57:43 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-165]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1386)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:99)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:58)
	at $Proxy0.prepareStatement(Unknown Source)
	at datomic.sql$update.invoke(sql.clj:51)
	at datomic.kv_sql.KVSql.put(kv_sql.clj:39)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120$fn__1121.invoke(kv_cluster.clj:190)
	at datomic.kv_cluster$retry_fn$fn__1051.invoke(kv_cluster.clj:76)
	at datomic.kv_cluster$retry_fn.invoke(kv_cluster.clj:76)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:607)
	at clojure.core$partial$fn__4074.doInvoke(core.clj:2347)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120.invoke(kv_cluster.clj:184)
	at datomic.kv_cluster.KVCluster$fn__1118.invoke(kv_cluster.clj:182)
	at clojure.core$binding_conveyor_fn$fn__3989.invoke(core.clj:1819)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
03-13 15:57:44 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-165]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1386)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:99)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:58)
	at $Proxy0.prepareStatement(Unknown Source)
	at datomic.sql$update.invoke(sql.clj:51)
	at datomic.kv_sql.KVSql.put(kv_sql.clj:39)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120$fn__1121.invoke(kv_cluster.clj:190)
	at datomic.kv_cluster$retry_fn$fn__1051.invoke(kv_cluster.clj:76)
	at datomic.kv_cluster$retry_fn.invoke(kv_cluster.clj:76)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:607)
	at clojure.core$partial$fn__4074.doInvoke(core.clj:2347)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120.invoke(kv_cluster.clj:184)
	at datomic.kv_cluster.KVCluster$fn__1118.invoke(kv_cluster.clj:182)
	at clojure.core$binding_conveyor_fn$fn__3989.invoke(core.clj:1819)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
03-13 15:57:44 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-165]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1386)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:99)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:58)
	at $Proxy0.prepareStatement(Unknown Source)
	at datomic.sql$update.invoke(sql.clj:51)
	at datomic.kv_sql.KVSql.put(kv_sql.clj:39)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120$fn__1121.invoke(kv_cluster.clj:190)
	at datomic.kv_cluster$retry_fn$fn__1051.invoke(kv_cluster.clj:76)
	at datomic.kv_cluster$retry_fn.invoke(kv_cluster.clj:76)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:607)
	at clojure.core$partial$fn__4074.doInvoke(core.clj:2347)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120.invoke(kv_cluster.clj:184)
	at datomic.kv_cluster.KVCluster$fn__1118.invoke(kv_cluster.clj:182)
	at clojure.core$binding_conveyor_fn$fn__3989.invoke(core.clj:1819)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
03-13 15:57:44 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-165]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1386)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:99)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:58)
	at $Proxy0.prepareStatement(Unknown Source)
	at datomic.sql$update.invoke(sql.clj:51)
	at datomic.kv_sql.KVSql.put(kv_sql.clj:39)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120$fn__1121.invoke(kv_cluster.clj:190)
	at datomic.kv_cluster$retry_fn$fn__1051.invoke(kv_cluster.clj:76)
	at datomic.kv_cluster$retry_fn.invoke(kv_cluster.clj:76)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:607)
	at clojure.core$partial$fn__4074.doInvoke(core.clj:2347)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120.invoke(kv_cluster.clj:184)
	at datomic.kv_cluster.KVCluster$fn__1118.invoke(kv_cluster.clj:182)
	at clojure.core$binding_conveyor_fn$fn__3989.invoke(core.clj:1819)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
03-13 15:57:44 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-165]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1386)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:99)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:58)
	at $Proxy0.prepareStatement(Unknown Source)
	at datomic.sql$update.invoke(sql.clj:51)
	at datomic.kv_sql.KVSql.put(kv_sql.clj:39)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120$fn__1121.invoke(kv_cluster.clj:190)
	at datomic.kv_cluster$retry_fn$fn__1051.invoke(kv_cluster.clj:76)
	at datomic.kv_cluster$retry_fn.invoke(kv_cluster.clj:76)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:607)
	at clojure.core$partial$fn__4074.doInvoke(core.clj:2347)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120.invoke(kv_cluster.clj:184)
	at datomic.kv_cluster.KVCluster$fn__1118.invoke(kv_cluster.clj:182)
	at clojure.core$binding_conveyor_fn$fn__3989.invoke(core.clj:1819)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
03-13 15:57:44 jdbc[9]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-165]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1386)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1361)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126)
	at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:99)
	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:58)
	at $Proxy0.prepareStatement(Unknown Source)
	at datomic.sql$update.invoke(sql.clj:51)
	at datomic.kv_sql.KVSql.put(kv_sql.clj:39)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120$fn__1121.invoke(kv_cluster.clj:190)
	at datomic.kv_cluster$retry_fn$fn__1051.invoke(kv_cluster.clj:76)
	at datomic.kv_cluster$retry_fn.invoke(kv_cluster.clj:76)
	at clojure.lang.AFn.applyToHelper(AFn.java:178)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:607)
	at clojure.core$partial$fn__4074.doInvoke(core.clj:2347)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at datomic.kv_cluster.KVCluster$fn__1118$fn__1120.invoke(kv_cluster.clj:184)
	at datomic.kv_cluster.KVCluster$fn__1118.invoke(kv_cluster.clj:182)
	at clojure.core$binding_conveyor_fn$fn__3989.invoke(core.clj:1819)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
